### ISSUE TITLE
Move to pytest-dev team? 

### ISSUE THREAD

**Issue by nicoddemus** [davehunt/pytest-browsermob-proxy#1]
Please consider moving to new [pytest-dev](https://github.com/orgs/pytest-dev) team. See [contributing](https://bitbucket.org/pytest-dev/pytest/src/e26175bf8246f01fc5573e92359b3124624c31b7/CONTRIBUTING.rst?at=default#rst-header-id8) for more information.

Cheers,

**Comment by davehunt** [comment]
I'm not actively maintaining this plugin, but I'm happy if someone wants it to be moved to pytest-dev to continue working on it. If so, please reopen this issue with details of whatever you need me to do. :)

**Comment by nicoddemus** [comment]
Thanks Dave. Can you post that question to pytest-dev@python.org, to see if any one steps up to it?

Cheers :smile:
